spring:
  application:
    name: auth-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/user_db
    username: postgres
    password: postgres #ENC(u2w5r7jsreXcrKIdbuqI183na97Rx2Z1)
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create


jasypt:
  encryptor:
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    algorithm: PBEWithMD5AndTripleDES

application:
  title: Auth Service
  version: 1.0

server:
  port: 9002

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    enabled: false

jwt-variables:
  EXPIRES_ACCESS_TOKEN_MINUTE: 999
  EXPIRES_REFRESH_TOKEN_MINUTE: 1
  ISSUER: dev
  KEY: asdqwe123+K3Y
